Godeps/Godeps.json, vendor/github.com/ghodss/yaml/README.md, vendor/github.com/ghodss/yaml/fields.go, vendor/github.com/ghodss/yaml/yaml.go
This PR is aiming to fix the build error in TravisCI. https://travis-ci.org/skippbox/kubewatch/jobs/264268646#L143
In the build `godep restore` fails as the `github.com/cloudfoundry-incubator/candiedyaml` dependency in `github.com/ghodss/yaml` has been renamed on Github.
The `github.com/ghodss/yaml` project already fixed https://github.com/ghodss/yaml/commit/b452f561ef721541543fb56c93b10b6afde66b93 it on their master, so this change only updates the dependency in Godep, and vendors the changes.
=> Updating dependency to fix build errors

README.md
As followup on #70, this improves the README with better installation instructions. It points to the helm chart, and updates the Slack information how to get a bot user installed.
=> Update README with bot and helm installation

cmd/resource.go, config/config.go, pkg/controller/controller.go, pkg/event/event.go
This PR finishes refactoring controller.go to use SharedIndexInformer and WorkQueue to monitor resource types. Then finish adding persistent volume, job and namespace resources for monitoring.
=> Refactor controller.go to finish use of SharedIndexInformer and WorkQueue, add namespace, persistent volume and job to resource types

README.md, pkg/controller/controller.go, pkg/event/event.go
This PR does the following:
- Point travis at the bitnami-labs endpoint instead of the previous skippbox endpoint
- Removes excessive code. Rather than having a controller function for each resource type, there's now a single resource controller. The informer is now created when checking the resource type (which was the only difference between the functions) and then the informer and resource type are now passed to the resourcecontroller function as parameters.
- Fixes an existing issue with the deployment resource type. Previously the deployment controller function was trying to return a service type (copy \ paste error on my part). This has been fixed and now allows deployment resources to be watched.
- Deployment resources now use the apps v1beta1 resource type. This fixes an error …
=> Code Cleanup and Deployment Fixes

pkg/controller/controller.go, pkg/utils/k8sutil.go
Hi, 
This PR, fixes issue reported in #51. 
kubewatch bombards the notification channel (say slack) with all the resources that were already present in the cluster. This is controlled by using `CreationTimestamp` properties available as part of object's metadata.
=> Fix for #51: listen only to latest events.

README.md, cmd/config.go, cmd/resource.go, cmd/webhook.go, config/config.go, config/config_test.go, examples/conf/kubewatch.conf.webhook.yaml, kubewatch-configmap.yaml, pkg/client/run.go, pkg/controller/controller.go, pkg/event/event.go, pkg/handlers/handler.go, pkg/handlers/webhook/webhook.go, pkg/handlers/webhook/webhook_test.go
In order to detect events described on https://github.com/bitnami-labs/sealed-secrets/issues/83, 
I needed to add support for Kubernetes secret object and simple support for a webhook handler.
=> Add secrets and wehook support

pkg/controller/controller.go, pkg/utils/k8sutil.go
By this way, the same binary can be executed indistinctly without any previous knowledge of the environment where is running
=> Try to autodetect when is running in-cluster or running from outside 

pkg/event/event.go
This way the messages should look like this:
A `pod` in namespace `staging` has been `deleted`:
`default/hello-world-aafdf56d8bc-r49fq`
=> Add markdown formatting to event message

Dockerfile, Dockerfile.run, Makefile, README.md
Use Docker's multi-stage builds to simplify the image building process.
=> Use multi-stage builds

config/config.go, kubewatch-configmap.yaml, pkg/controller/controller.go
today, kubewatch watches the events in all namespace, while in my case, i'd like to avoid suck massive events flow, so i'd like to watch events in specific namespace
=> add config for watching on specific namespace rather than all

README.md
https://github.com/kubernetes/charts/pull/3482 graduates the Helm chart for kubewatch to stable. Since `stable` is included as a repo in `helm` by default, I've also removed the `helm repo add` instruction.
=> Reference stable helm chart for kubewatch

cmd/config.go, cmd/msteams.go, config/config.go, examples/conf/kubewatch.conf.msteams.yaml, pkg/client/run.go, pkg/handlers/handler.go, pkg/handlers/msteam/msteam.go, pkg/handlers/msteam/msteam_test.go
MS Teams is now natively integrated with Kubewatch. The configuration
can be provided for posting on to the MS Teams incoming webhook
connector.
The implementation is inspired from the MS Teams and Prometheus
alerts integration by https://github.com/bzon/prometheus-msteams
Fixes #134
=> Adds support for MS Teams natively using webhooks

README.md, cmd/config.go, pkg/client/run.go, pkg/handlers/flock/flock.go, pkg/handlers/handler.go, pkg/handlers/hipchat/hipchat.go, pkg/handlers/mattermost/mattermost.go, pkg/handlers/msteam/msteam.go, pkg/handlers/msteam/msteam_test.go, pkg/handlers/slack/slack.go, pkg/handlers/webhook/webhook.go
This commit 
- adds `config test` subcommand to send test messages to handlers(webhooks).
- lints code using `gofmt -w -s .` to lint code.
- Updates README.md regarding this new feature.
This feature eliminates the need for creating/deleteing dummy Kubernetes objects for testing the notification functionality of kubewatch. 
Now we could use the `kubewatch config test` to send test messages to the slack channel or the configured handler.
```
$ kubewatch config test
Testing Handler configs from .kubewatch.yaml
2019/06/03 13:21:23 Message successfully sent to channel GGF5T7H8F at 1559548283.000100
```
@tylerauerbeck  @jbianquetti-nami @jjo 
looking for comments and feedbacks :+1:
=> Feature: "config test" subcommand fot testing Webhooks/Handlers. 

Dockerfile
- Replace Alpine by minideb
- `git` already installed:
```
Step 3/9 : RUN apt-get update && apt-get install -y --no-install-recommends git build-essential
---> Running in 9843c12aff27
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [93.6 kB]
Get:3 http://deb.debian.org/debian stretch-updates InRelease [90.3 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch Release.gpg [2434 B]
Get:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [499 kB]
Get:7 http://deb.debian.org/debian stretch-updates/main amd64 Packages [27.2 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [7082 kB]
Fetched 7912 kB in 1s (5143 kB/s) …
```
=> Replace Alpine by minideb

README.md
The stable helm repo has been deprecated; indeed if you go to https://github.com/helm/charts/tree/master/stable/kubewatch you'll see a deprecation warning pointing to bitnami/kubewatch.
In the meantime all the updates have gone to bitnami/kubewatch and thus users following this README
are installing the wrong thing.
=> Update readme to point to new location of helm chart

Makefile
it's been a few releases of the Go toolchain that the vendor dir is excluded from the ./... pattern
and thus we can remove the kludge.
=> Simplify make test

pkg/controller/controller.go, pkg/event/event.go
v1beta.Deployment got deprecated in v1.16.x in favour of apps/v1.Deployment (available since v1.9)
similar for other types.
Closes #200
=> Switch to apps/v1.Deployment and friends

cmd/root.go, pkg/controller/controller.go, pkg/event/event.go, pkg/handlers/flock/flock.go, pkg/handlers/hipchat/hipchat.go, pkg/handlers/mattermost/mattermost.go, pkg/handlers/msteam/msteam.go, pkg/handlers/msteam/msteam_test.go, pkg/handlers/slack/slack.go, pkg/handlers/webhook/webhook.go, pkg/utils/k8sutil.go
This PR addresses #129 and #106,
- alerts on CrashLoopBackOff events occurring in pods ( when pods are being watched )
- alerts on cluster level critical events like 
- NodeNotReady
- NodeReady
- NodeRebooted (by default)
- removes New() func from event pkg to enhance simplicity
- removes action filed from notify function in all handlers to enhance simplicity 
- retrieves namespace value and name from event key, if empty.
- modified msteam_test.go suitably to test functionalities.
- minor bug fixes
- fixing typos
Thoughts and Comments..?
=> Notify Cluster Level Critical Events and CrashLoopBackOff Events in pods

cmd/config.go, pkg/controller/controller.go, pkg/handlers/flock/flock.go, pkg/handlers/handler.go, pkg/handlers/hipchat/hipchat.go, pkg/handlers/mattermost/mattermost.go, pkg/handlers/msteam/msteam.go, pkg/handlers/msteam/msteam_test.go, pkg/handlers/slack/slack.go, pkg/handlers/smtp/smtp.go, pkg/handlers/webhook/webhook.go
The `interface{}` arguments were incredibly confusing (what kind of object was that? an object, an event?)
Furthermore turns out that all the handler implementations funneled all events through a generic "notifyFoo"
function. The even itself contains the kind of action (Created, Updated etc) so it really doesn't make
sense to have N handler methods one for each kind.
Also, the notification config test is handled though the same codepath as sending an actual notification;
having to duplicate the code for test was error prone.
=> Simplify handler interface

cmd/config.go, config/config.go, config/sample.go, go.mod, go.sum, tools/yannotated/yannotated.go, tools/yannotated/yannotated_test.go
```
$ kubewatch config sample
handler:
slack:
token: ""
channel: ""
title: ""
....
```
TODO: update add/remove commands to use go-yaml-edit to perform in-place edits in the yaml file while preserving the comments.
=> Add automatically generated config sample
